apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-ex
  labels:
    app: myapp
spec:
  template:
    spec:
      metadata:
        name: nginx
        labels:
          app: myapp
      spec:
        containers:
          - name: data
            image: nginx

  replicas: 3
  selector:
    matchLabels:
      app: myapp

